spring:
  datasource:
    url: jdbc:h2:mem:routesdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

app:
  route-map:
    atmCount: 1000
  collector:
    count: 5