spring:
  datasource:
    url: jdbc:h2:mem:routesdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

app:
  generator:
    route-map:
      atmCount: 10
    collector:
      count: 5